### ISSUE TITLE
Update new user docs for prod deployment

### ISSUE THREAD

**Issue by t-young31** [UCLH-Foundry/Garden-Path#11]
urls have changed thus should be updated in the notebooks

**Comment by dram1964** [comment]
I think the DICOM URL has changed from https://hdsflowehrdev-dicom-flowehr-dev.dicom.azurehealthcareapis.com to https://hdspixldflowehrprod-dicom-pixld-flowehr-prod.dicom.azurehealthcareapis.com

**Comment by dram1964** [comment]
Suspect the Data Lake changes are: 

- stflowehrdev -> stpixldflowehrprod
- data-lake-storage-flowehr-dev -> data-lake-storage-pixld-flowehr-prod
