### ISSUE TITLE
Make 'garden-path' a subdomain of FlowEHR.io

### ISSUE THREAD

**Issue by docsteveharris** [UCLH-Foundry/Garden-Path#22]
Can the github.io site (`https://uclh-foundry.github.io/Garden-Path/`) be linked to `docs.flowehr.io`

**Comment by nels** [comment]
I put in a redirect from `http://docs.flowehr.io` to `https://uclh-foundry.github.io/Garden-Path/`
Not sure how Quarto deployment differs from GH Pages deployment but it's not possible to add a CNAME record for a path on a host, only directly for a host.
Closing _for now_ and can revisit a proper deployment behind `https://docs.flowehr.io`
